### PR TITLE
Guard friendly_tangent_cache array branch against NoTangent eltypes

### LINKED ISSUE #1149: Crash with sparse matrix when friendly_tangents=true in Mooncake 0.5.25 (works in 0.5.24)
The sparse matrix inputs fail when using `friendly_tangents = true` with Mooncake 0.5.25 and above.
However it works on Mooncake 0.5.24 (julia 1.12.5).

MWE:
```julia
using Mooncake, SparseArrays

A = sparse([1,2], [1,2], [1,2], 2, 2)
f(A) = sum(Float64, A.nzval)

println("forward = ", f(A))

cache = Mooncake.prepare_gradient_cache(
    f,
    A;
    config = Mooncake.Config(friendly_tangents=true),
)
out = Mooncake.value_and_gradient!!(cache, f, A)
println(out)
```
It produces this error and stacktrace:
```bash
ERROR: MethodError: no method matching zero(::Mooncake.FriendlyTangentCache{Mooncake.AsRaw, Nothing})
The function `zero` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  zero(::Type{Union{}}, Any...)
   @ Base number.jl:315
  zero(::Type{Dates.DateTime})
   @ Dates ~/.julia/juliaup/julia-1.12.5+0.x64.linux.gnu/share/julia/stdlib/v1.12/Dates/src/types.jl:458
  zero(::Type{Dates.Date})
   @ Dates ~/.julia/juliaup/julia-1.12.5+0.x64.linux.gnu/share/julia/stdlib/v1.12/Dates/src/types.jl:459
  ...

Stacktrace:
  [1] iszero(x::Mooncake.FriendlyTangentCache{Mooncake.AsRaw, Nothing})
    @ Base ./number.jl:42
  [2] _iszero
    @ ~/.julia/juliaup/julia-1.12.5+0.x64.linux.gnu/share/julia/stdlib/v1.12/SparseArrays/src/SparseArrays.jl:43 [inlined]
  [3] _noshapecheck_map
    @ ~/.julia/juliaup/julia-1.12.5+0.x64.linux.gnu/share/julia/stdlib/v1.12/SparseArrays/src/higherorderfns.jl:181 [inlined]
  [4] map
    @ ~/.julia/juliaup/julia-1.12.5+0.x64.linux.gnu/share/julia/stdlib/v1.12/SparseArrays/src/higherorderfns.jl:1187 [inlined]
  [5] macro expansion
    @ ~/.julia/packages/Mooncake/O5brV/src/tangents/tangents.jl:-1 [inlined]
  [6] friendly_tangent_cache
    @ ~/.julia/packages/Mooncake/O5brV/src/tangents/tangents.jl:1392 [inlined]
  [7] map(f::typeof(Mooncake.friendly_tangent_cache), t::Tuple{typeof(f), SparseMatrixCSC{Int64, Int64}})
    @ Base ./tuple.jl:359
  [8] prepare_gradient_cache(::Function, ::Vararg{Any}; config::Mooncake.Config)
    @ Mooncake ~/.julia/packages/Mooncake/O5brV/src/interface.jl:794
  [9] top-level scope
    @ none:6
 [10] eval(m::Module, e::Any)
    @ Core ./boot.jl:489
 [11] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:283
 [12] _start()
    @ Base ./client.jl:550
```

### PR DESCRIPTION
**Pull request by yebai**
Add `tangent_type(eltype(P)) != NoTangent` to the array-recursion guard in `friendly_tangent_cache`. For integer-element sparse arrays,                
  `tangent_type(Int64) == NoTangent`, so the `map` is skipped and the cache falls through to `FriendlyTangentCache{AsRaw}` — the correct result since the
   elements are non-differentiable.                                                                                                                      
                                                                      
  The call to `tangent_type` in the generator body is safe here: every type for which `tangent_type == NoTangent` has an explicit, non-generated method, 
  so no generated dispatch occurs at generation time.
                                                                                                                                                         
  Fixes #1149 -- note the fix is not specific to SparseArrays and affect Arrays of Integers too.

### Documentation Preview

Mooncake.jl documentation for PR #1150 is available at:
https://chalk-lab.github.io/Mooncake.jl/previews/PR1150/

### Performance

Performance Ratio:
Ratio of time to compute gradient and time to compute function.
Warning: results are very approximate! See [here](https://github.com/chalk-lab/Mooncake.jl/tree/main/bench#inter-framework-benchmarking) for more context.
```
┌───────────────────────┬──────────┬──────────┬─────────────┬─────────┬─────────────┬────────┐
│                 Label │   Primal │ Mooncake │ MooncakeFwd │  Zygote │ ReverseDiff │ Enzyme │
│                String │   String │   String │      String │  String │      String │ String │
├───────────────────────┼──────────┼──────────┼─────────────┼─────────┼─────────────┼────────┤
│              sum_1000 │ 171.0 ns │     1.64 │         1.7 │    0.76 │        3.87 │   7.38 │
│             _sum_1000 │   1.1 μs │     5.97 │        1.02 │  4430.0 │        40.3 │   1.06 │
│          sum_sin_1000 │  7.42 μs │     2.47 │        1.11 │    1.63 │        10.9 │    1.8 │
│         _sum_sin_1000 │  4.61 μs │     3.86 │        2.65 │   359.0 │        17.7 │   3.08 │
│              kron_sum │ 193.0 μs │     13.0 │        3.32 │    7.13 │       500.0 │   18.2 │
│         kron_view_sum │ 264.0 μs │     12.9 │        5.32 │    29.6 │       375.0 │   6.86 │
│ naive_map_sin_cos_exp │  2.21 μs │     2.82 │        1.53 │ missing │        8.33 │   2.15 │
│       map_sin_cos_exp │  2.21 μs │     3.35 │        1.61 │    1.53 │        7.18 │   2.67 │
│ broadcast_sin_cos_exp │   2.3 μs │     3.15 │        1.56 │     4.2 │        1.42 │   2.11 │
│            simple_mlp │ 345.0 μs │     5.02 │        2.94 │     2.0 │        9.72 │    3.2 │
│                gp_lml │ 371.0 μs │     5.98 │        1.76 │    3.13 │     missing │   3.22 │
│    large_single_block │ 471.0 ns │     8.08 │        1.96 │  4130.0 │        36.0 │   2.06 │
└───────────────────────┴──────────┴──────────┴─────────────┴─────────┴─────────────┴────────┘
```

### CODE REVIEW

**Comment by yebai** [comment]
@AstitvaAggarwal, can you help take over and release?

**Comment by AstitvaAggarwal** [comment]
@yebai do I take over this/is this ready? I ask because I saw u pushing more commits to this PR

**Comment by yebai** [comment]
@sunxd3 / @AstitvaAggarwal, this should be ready for reviewing and merging.

File: src/tangents/tangents.jl [hunk 1]
```diff
@@ -1382,11 +1382,11 @@ caches instead.
 |---|---|
 | Immutable struct with fields and standard `Tangent` | `NamedTuple` of per-field caches *(composite)* |
 | `Tuple` | `Tuple` of per-element caches *(composite)* |
-| `AbstractArray` with non-float eltype | `Array` of per-element caches via `map` *(composite)* |
+| `AbstractArray` with non-float, non-`NoTangent` eltype | `Array` of per-element caches via `map` *(composite)* |
```
Comment (AstitvaAggarwal) [inline src/tangents/tangents.jl]:
```suggestion
| `AbstractArray` with non-float eltype whose `tangent_type` is not `NoTangent` | `Array` of per-element caches via `map` *(composite)* |
```

File: src/tangents/tangents.jl [hunk 2]
```diff
@@ -1449,8 +1449,13 @@ Overloads for `LinearAlgebra.Symmetric`, `LinearAlgebra.Hermitian`, and
...
     end
-    # Array whose elements are non-primitive structs: recurse element-wise.
-    if P <: AbstractArray && !(eltype(P) <: Union{IEEEFloat,Complex{<:IEEEFloat}})
+    # Skip non-differentiable eltypes: avoids pointless caches and map on sparse containers.
+    # Calling tangent_type in a generator body risks world-age cycles, but is safe here:
+    # every eltype for which tangent_type == NoTangent (integers, Bool, Symbol, …) has an
+    # explicit non-generated method, so no generated dispatch occurs at generation time.
+    if P <: AbstractArray &&
+        !(eltype(P) <: Union{IEEEFloat,Complex{<:IEEEFloat}}) &&
+        tangent_type(eltype(P)) != NoTangent
```
Comment (AstitvaAggarwal) [inline src/tangents/tangents.jl:1459]: The comment says all `NoTangent` types have explicit non-generated `tangent_type` methods, but `tangent_type(Tuple{Int,Int})` returns `NoTangent` via the `@generated` at line `416`, so that's not completely right. Also technically violates `AGENTS.md`. Currently PR works because `tangent_type` is `@foldable`, but worth noting?

Comment (yebai) [reply src/tangents/tangents.jl:1459]: @AstitvaAggarwal / @sunxd3 feel free to take this forward: fix all issues and get it merged.
