### PR TITLE
Fix differentiating GPU Dense layer (#910)

### LINKED ISSUE #910: missing GPU rules required by Flux
```julia
import DifferentiationInterface as DI
using CUDA, cuDNN, Mooncake, Flux

x = rand(Float32, 2)
model = Dense(2, 2)

### ON CUDA GPU
x_gpu = x |> gpu
model_gpu = model |> gpu
g_gpu = DI.gradient(m -> sum(m(x_gpu)), DI.AutoMooncake(), model_gpu) # had to interrupt, was taking several minutes
```

Courtesy: https://github.com/FluxML/Flux.jl/issues/2640#issuecomment-3684454960

cc @CarloLucibello

### LINKED ISSUE #996: Failure with basic Flux Chain on GPU
The following basic experiment on support for Flux's Chain, I hit issue when testing on GPU/CUDA.

### Setup:
```julia
using Random
using CUDA
using Flux, Optimisers
using Statistics: mean
import DifferentiationInterface as DI
import Mooncake as MC
Random.seed!(123)
```

### Model definition
```julia
m = Chain(Dense(3, 3, relu), Dense(3, 1))
myloss(m, x, y) = mean((m(x) .- y) .^ 2)
x, y = randn(Float32, 3, 4), randn(Float32, 4)
myloss(m, x, y)
```

### Test on CPU: works fine
```julia
cache = MC.prepare_gradient_cache(myloss, m, x, y; config=MC.Config(; friendly_tangents=true));
val, grads = MC.value_and_gradient!!(cache, myloss, m, x, y)
opts = Optimisers.setup(Adam(), m)
NeuroTabModels.Fit.Optimisers.update!(opts, m, grads[2])
```

### Test on GPU: `prepare_gradient_cache` fails
```julia
mg, xg, yg = (m, x, y) .|> gpu
cache = MC.prepare_gradient_cache(myloss, mg, xg, yg; config=MC.Config(; friendly_tangents=true));

ERROR: MooncakeRuleCompilationError: an error occurred while Mooncake was compiling a rule to differentiate something. If the `caused by` error message below does not make it clear to you how the problem can be fixed, please open an issue at github.com/chalk-lab/Mooncake.jl describing your problem.
To replicate this error run the following:

Mooncake.build_rrule(Mooncake.MooncakeInterpreter(Mooncake.ReverseMode), Tuple{typeof(LinearAlgebra.generic_matmatmul!), CuArray{Float32, 2, CUDA.DeviceMemory}, Char, Char, CuArray{Float32, 2, CUDA.DeviceMemory}, CuArray{Float32, 2, CUDA.DeviceMemory}, Bool, Bool}; debug_mode=false)

Note that you may need to `using` some additional packages if not all of the names printed in the above signature are available currently in your environment.

...
caused by: CUDA.CUBLAS.cublasComputeType_t is a primitive type. Implement a method of `tangent_type` for it.
Stacktrace:
  [1] error(s::String)
    @ Base .\error.jl:35
  [2] #s11#56
    @ C:\Users\jerem\.julia\packages\Mooncake\xbBlx\src\tangents\tangents.jl:472 [inlined]
...
```

Note sure if the error message relating to `CUDA.CUBLAS.cublasComputeType_t` is just a red herring here; it seems suspicious that such basic GPU operation would fail. 

I'm on Windows, using latests Mooncake release (0.5.4)

### PR DESCRIPTION
**Pull request by yebai**
Fixes #910 Fix #996

 Differentiating through a Flux `Dense` layer on CUDA fails because Mooncake
 traces into GPU internals containing types with no `tangent_type`/`fdata_type`
 methods. Two primitive rules intercept before the problematic code:

   - **`ext/MooncakeCUDAExt.jl`** — [`LinearAlgebra.mul!(C, A, B)` on `CuArray`](https://github.com/JuliaGPU/CUDA.jl/blob/3405d7f5484ff69a9ae4885b241a871bf8f07928/lib/cublas/linalg.jl#L395-L398)
   Registers `@is_primitive` + `frule!!` + `rrule!!` for 3-arg `mul!` on
   `CuMaybeComplexArray` (real and complex `IEEEFloat`, matrix×matrix and
   matrix×vector). Gradients: `dA += dC * B'`, `dB += A' * dC`.

   - **`ext/MooncakeNNlibExt.jl`** — add `NNlib.bias_act!(identity, x, b)` rules on GPU and CPU. 

   - **Tests:** `mul!` cases in `test/ext/cuda/cuda.jl`; `bias_act!` cases in
   `test/ext/nnlib/nnlib.jl` (runs on CPU and CUDA).

### CODE REVIEW

File: ext/MooncakeCUDAExt.jl [hunk 1]
```diff
@@ -251,4 +253,46 @@ function rrule!!(::CoDual{typeof(sum)}, x::CoDual{<:CuFloatArray})
     return zero_fcodual(sum(identity, x.x)), sum_pb!!
 end
 
+# Rules for the 3-arg mul!(C, A, B) on GPU arrays. Registering as a primitive
+# prevents Mooncake from tracing into CUBLAS internals (which contain types such
+# as cublasComputeType_t that have no tangent_type method).
```
Comment (yebai) [inline ext/MooncakeCUDAExt.jl]:
```suggestion
# Rules for the 3-arg mul!(C, A, B) on GPU arrays.
```

File: ext/MooncakeCUDAExt.jl [hunk 2]
```diff
@@ -235,12 +237,12 @@ function rrule!!(
...
+# Rule for `sum` is defined as a performance rule.
+# See also `src/rules/performance_patches`.
 @is_primitive(DefaultCtx, Tuple{typeof(sum),CuFloatArray})
 function frule!!(::Dual{typeof(sum)}, x::Dual{<:CuFloatArray})
-    return Dual(sum(primal(x)), sum(tangent(x)))
+    px, dx = arrayify(x)
+    return Dual(sum(px), sum(dx))
 end
 function rrule!!(::CoDual{typeof(sum)}, x::CoDual{<:CuFloatArray})
     dx = x.dx
```
Comment (yebai) [inline ext/MooncakeCUDAExt.jl]:
```suggestion
    _, dx = arrayify(x)
```

File: ext/MooncakeNNlibExt.jl [hunk 3]
```diff
@@ -72,4 +83,46 @@ for pool in [:maxpool, :meanpool]
...
+    return x
+end
+function rrule!!(
+    ::CoDual{typeof(bias_act!)},
+    ::CoDual{typeof(identity)},
+    x::CoDual{<:GPUIEEEArray{T,N}},
+    b::CoDual{<:GPUIEEEArray},
+) where {T,N}
+    px, dx = primal(x), tangent(x)
+    pb, db = primal(b), tangent(b)
```
Comment (yebai) [inline ext/MooncakeNNlibExt.jl]:
```suggestion
    px, dx = arrayify(x)
    pb, db = arrayify(b)
```

**Comment by AstitvaAggarwal** [comment]
Looks good

**Review by AstitvaAggarwal — COMMENTED** [review]
@yebai did you check the tests with the `stability` flag? I think amost all the added tests cases will pass for those additional tests.

**Comment by yebai** [comment]
@AstitvaAggarwal, can you help do that? Feel free to take over this PR.

**Comment by AstitvaAggarwal** [comment]
@yebai I have added a change for parametric methods and `SupportedArray`'s type specification (results in faster dispatch when using rules etc. that use `SupportedArray` ). Ill merge when all CI passes.
