### PR TITLE
Fix `tangent_type` world age issue in `build_output_tangent`

### LINKED ISSUE #893: `tangent_type(::Type) = NoTangent` not respected in Forward Mode?
I'm testing `AutoMooncakeForward` in https://github.com/mlange-42/Ark.jl/actions/runs/20253581131/job/58150732551?pr=426 and I got a stackoverflow error:

```julia
ERROR: StackOverflowError:
Stacktrace:
      [1] macro expansion
        @ ~/.julia/dev/Mooncake/src/tangents.jl:487 [inlined]
      [2] macro expansion
        @ ./none:0 [inlined]
      [3] tangent_type(::Type{Ark._GraphNode{1}})
        @ Mooncake ./none:0
      [4] tangent_type(::Type{Vector{Ark._GraphNode{1}}})
        @ Mooncake ~/.julia/dev/Mooncake/src/tangents.jl:354
      [5] macro expansion
        @ ~/.julia/dev/Mooncake/src/tangents.jl:487 [inlined]
      [6] macro expansion
        @ ./none:0 [inlined]
      [7] tangent_type(::Type{Ark._VecMap{Ark._GraphNode{1}, 1}})
        @ Mooncake ./none:0
--- the last 3 lines are repeated 1 more time ---
--- the last 7 lines are repeated 26659 more times ---
 [186624] tangent_type(::Type{Vector{Ark._GraphNode{1}}})
        @ Mooncake ~/.julia/dev/Mooncake/src/tangents.jl:354
 [186625] macro expansion
        @ ~/.julia/dev/Mooncake/src/tangents.jl:487 [inlined]
 [186626] macro expansion
        @ ./none:0 [inlined]
 [186627] tangent_type(::Type{Ark._VecMap{Ark._GraphNode{1}, 1}})
        @ Mooncake ./none:0
 [186628] macro expansion
        @ ~/.julia/dev/Mooncake/src/tangents.jl:487 [inlined]
 [186629] macro expansion
        @ ./none:0 [inlined]
```

I'm not getting why though since reverse mode works and I have in the library these lines:

```julia
Mooncake.tangent_type(::Type{<:Ark._GraphNode}) = Mooncake.NoTangent
Mooncake.tangent_type(::Type{<:Ark._VecMap}) = Mooncake.NoTangent
Mooncake.tangent_type(::Type{<:Ark._EventManager}) = Mooncake.NoTangent
```

which should remove the recursion. Is there anything blocking the usage of these definitions in forward mode?

<details> <summary>MWE </summary>

```julia
julia> using Ark # needs the dev version

julia> using DifferentiationInterface

julia> using Mooncake

julia> using Random

julia> function run_world(args)
               alpha, beta = args
               world = World(Position, Velocity)

               entities = Entity[]
               sizehint!(entities, 100)
               for i in 1:100
                   entity = new_entity!(world, (Position(i, i * 2),))
                   push!(entities, entity)
               end

               for e in entities
                   add_components!(world, e, (Velocity(1, 1),))
               end

               for i in 1:10
                   for (entities, positions, velocities) in Query(world, (Position, Velocity))
                       @inbounds for i in eachindex(entities)
                           pos = positions[i]
                           vel = velocities[i]
                           positions[i] = Position(alpha * (pos.x + vel.dx), beta * (pos.y + vel.dy))
                       end
                   end
               end

               all_positions = Position[]
               for (entities, positions) in Query(world, (Position,))
                   append!(all_positions, positions)
               end

               return sum(pos.x + pos.y for pos in all_positions)
           end
run_world (generic function with 1 method)

julia> backend = AutoMooncakeForward()
AutoMooncakeForward()

julia> struct Velocity
           dx::Float64
           dy::Float64
       end

julia> struct Position
           x::Float64
           y::Float64
       end

julia> struct Velocity
           dx::Float64
           dy::Float64
       end

julia> g = gradient(run_world, backend, [0.1, 0.5])
ERROR: StackOverflowError:
Stacktrace:
      [1] macro expansion
        @ ~/.julia/dev/Mooncake/src/tangents.jl:487 [inlined]
      [2] macro expansion
        @ ./none:0 [inlined]
      [3] tangent_type(::Type{Ark._GraphNode{1}})
        @ Mooncake ./none:0
      [4] tangent_type(::Type{Vector{Ark._GraphNode{1}}})
        @ Mooncake ~/.julia/dev/Mooncake/src/tangents.jl:354
      [5] macro expansion
        @ ~/.julia/dev/Mooncake/src/tangents.jl:487 [inlined]
      [6] macro expansion
        @ ./none:0 [inlined]
      [7] tangent_type(::Type{Ark._VecMap{Ark._GraphNode{1}, 1}})
        @ Mooncake ./none:0
--- the last 3 lines are repeated 1 more time ---
--- the last 7 lines are repeated 26659 more times ---
 [186624] tangent_type(::Type{Vector{Ark._GraphNode{1}}})
        @ Mooncake ~/.julia/dev/Mooncake/src/tangents.jl:354
 [186625] macro expansion
        @ ~/.julia/dev/Mooncake/src/tangents.jl:487 [inlined]
 [186626] macro expansion
        @ ./none:0 [inlined]
 [186627] tangent_type(::Type{Ark._VecMap{Ark._GraphNode{1}, 1}})
        @ Mooncake ./none:0
 [186628] macro expansion
        @ ~/.julia/dev/Mooncake/src/tangents.jl:487 [inlined]
 [186629] macro expansion
        @ ./none:0 [inlined]
```
</details>

### PR DESCRIPTION
**Pull request by yebai**
## Summary

Fix world-age issues in `build_output_tangent` where `@generated` functions could not see user-defined `tangent_type` methods for custom/recursive types.

Fixes #893

### `src/rules/new.jl`
- Refactored `build_output_tangent` to compute `tangent_field_types(P)` and `tangent_type(P)` at **runtime** instead of compile time
- Split into `build_output_tangent` (inline wrapper) and `_build_output_tangent_cartesian` (`@generated` function using `Base.Cartesian.@ntuple`)
- This ensures user-defined `tangent_type` methods are visible regardless of when they were defined

### Tests
- Consolidated regression tests into `test/rules/tangent_world_age_regression.jl`
- Tests cover `build_fdata`, `build_fdata` nested, and `build_output_tangent` with recursive custom tangent types
- Removed duplicate test files

### Other
- Version bump to 0.5.9

### CODE REVIEW

File: src/rules/new.jl [hunk 1]
```diff
@@ -55,8 +55,8 @@ end
             return :($F())
         end
     end
-    T_out = tangent_type(P)
-    return :($T_out(NamedTuple{$names}($(Expr(:call, tuple, tangent_exprs...)))))
+    # Compute tangent_type at runtime to ensure extension methods are available
```
Comment (yebai) [inline src/rules/new.jl]:
```suggestion
    # compute `tangent_type` at runtime to avoid world-age issues, see #1008

```

File: test/rules/build_fdata_world_age_regression.jl [hunk 2]
```diff
@@ -71,6 +71,13 @@ using Test
             TestWrapper{TestRecursiveA{Float32}}, (a,), fdata_tuple
         )
         @test result isa Mooncake.FData{@NamedTuple{x::TangentForTestRecursiveA{Float32}}}
+
+        # Test build_output_tangent uses runtime tangent_type (related fix)
```
Comment (yebai) [inline test/rules/build_fdata_world_age_regression.jl]:
```suggestion
        # Test `build_output_tangent` uses runtime `tangent_type`, see #1008

```

File: src/rules/new.jl
Comment (sunxd3) [inline src/rules/new.jl]: #893 will still likely to fail because `tangent_field_types` is called at compile time

File: test/rules/build_output_tangent_world_age_regression.jl [hunk 3]
```diff
@@ -0,0 +1,94 @@
+
```
Comment (sunxd3) [inline test/rules/build_output_tangent_world_age_regression.jl]:
```suggestion
```

**Comment by yebai** [comment]
This PR looks good to me -- happy to merge as is!
