### PR TITLE
Fix @from_chainrules to respect mode parameter (#882)

### LINKED ISSUE #882: `@from_chainrules` does not respect mode argument
```julia
julia> @macroexpand @from_chainrules DefaultCtx Tuple{typeof(foo)} true ForwardMode
quote
    #= /Users/pyong/ppl/mooncake/src/tools_for_rules.jl:678 =#
    function (Mooncake.Mooncake)._is_primitive(::Mooncake.Type{DefaultCtx}, ::Mooncake.Type{<:Mooncake.ForwardMode}, ::Mooncake.Type{<:Tuple{typeof(foo)}})
        #= /Users/pyong/ppl/mooncake/src/tools_for_rules.jl:678 =#
        #= /Users/pyong/ppl/mooncake/src/tools_for_rules.jl:681 =#
        return true
    end
    #= /Users/pyong/ppl/mooncake/src/tools_for_rules.jl:683 =#
    function (Mooncake.Mooncake).frule!!(var"#196#x_1"::(Mooncake.Mooncake).Dual{<:typeof(foo)})
        (Mooncake.frule_wrapper)(var"#196#x_1")
    end
    #= /Users/pyong/ppl/mooncake/src/tools_for_rules.jl:684 =#
    function (Mooncake.Mooncake).rrule!!(var"#197#x_1"::(Mooncake.Mooncake).CoDual{<:typeof(foo)})
        (Mooncake.rrule_wrapper)(var"#197#x_1")
    end
    #= /Users/pyong/ppl/mooncake/src/tools_for_rules.jl:685 =#
    begin
        #= /Users/pyong/ppl/mooncake/src/tools_for_rules.jl:647 =#
        function (Mooncake.Mooncake)._is_primitive(::Mooncake.Type{DefaultCtx}, ::Mooncake.Type{<:Mooncake.ForwardMode}, ::Mooncake.Type{<:Mooncake.Tuple{Mooncake.typeof((Mooncake.Core).kwcall), Mooncake.NamedTuple, typeof(foo)}})
            #= /Users/pyong/ppl/mooncake/src/tools_for_rules.jl:647 =#
            #= /Users/pyong/ppl/mooncake/src/tools_for_rules.jl:650 =#
            return true
        end
    end
    #= /Users/pyong/ppl/mooncake/src/tools_for_rules.jl:686 =#
    function (Mooncake.Mooncake).frule!!(var"#199#_kwcall"::(Mooncake.Mooncake).Dual{Mooncake.typeof((Mooncake.Core).kwcall)}, var"#200#kwargs"::(Mooncake.Mooncake).Dual{<:Mooncake.NamedTuple}, var"#201#x_1"::(Mooncake.Mooncake).Dual{<:typeof(foo)})
        (Mooncake.frule_wrapper)(var"#199#_kwcall", var"#200#kwargs", var"#201#x_1")
    end
    #= /Users/pyong/ppl/mooncake/src/tools_for_rules.jl:687 =#
    function (Mooncake.Mooncake).rrule!!(var"#202#_kwcall"::(Mooncake.Mooncake).CoDual{Mooncake.typeof((Mooncake.Core).kwcall)}, var"#203#kwargs"::(Mooncake.Mooncake).CoDual{<:Mooncake.NamedTuple}, var"#204#x_1"::(Mooncake.Mooncake).CoDual{<:typeof(foo)})
        (Mooncake.rrule_wrapper)(var"#202#_kwcall", var"#203#kwargs", var"#204#x_1")
    end
end
```

If you strip away the line numbers, prefixes and mangling this is

```julia
function _is_primitive(::Type{DefaultCtx}, ::Type{<:ForwardMode}, ::Type{<:Tuple{typeof(foo)}})
    return true
end
function frule!!(x_1::Dual{<:typeof(foo)})
    frule_wrapper(x_1)
end
function rrule!!(x_1::CoDual{<:typeof(foo)})
    rrule_wrapper(x_1)
end
function _is_primitive(::Type{DefaultCtx}, ::Type{<:ForwardMode}, ::Type{<:Tuple{typeof((Core).kwcall), NamedTuple, typeof(foo)}})
    return true
end
function frule!!(_kwcall::Dual{typeof(Core.kwcall)}, kwargs::Dual{<:NamedTuple}, x_1::Dual{<:typeof(foo)})
    frule_wrapper(_kwcall, kwargs, x_1)
end
function rrule!!(_kwcall::CoDual{typeof(Core.kwcall)}, kwargs::CoDual{<:NamedTuple}, x_1::CoDual{<:typeof(foo)})
    rrule_wrapper(_kwcall, kwargs, x_1)
end
```

The only part that obeys the mode argument is `_is_primitive`; I wouldn't expect the rrules to be defined.

### PR DESCRIPTION
**Pull request by sunxd3**
Fix #882

### CODE REVIEW

File: src/tools_for_rules.jl [hunk 1]
```diff
@@ -629,6 +629,8 @@ case because the required method of either of these functions does not exist, pl
 issue.
 """
 macro from_chainrules(ctx, sig::Expr, has_kwargs::Bool=false, mode=Mode)
+    mode = mode == :ForwardMode ? ForwardMode : mode
```
Comment (Technici4n) [inline src/tools_for_rules.jl:632]: Should we throw if mode is neither `Mode`, `:ForwardMode`, `:ReverseMode`?

File: src/tools_for_rules.jl [hunk 2]
```diff
@@ -651,42 +666,58 @@ function _from_chainrules_impl(ctx, sig::Expr, has_kwargs::Bool, mode)
...
             return true
         end
-        $frule_expr
-        $rrule_expr
-        $kw_is_primitive
-        $kwargs_frule_expr
-        $kwargs_rrule_expr
     end
+
+    exprs = filter(
```
Comment (Technici4n) [inline src/tools_for_rules.jl:718]: Technically the filter is not needed, right? But I suppose it doesn't hurt.

File: src/tools_for_rules.jl (hunk 1 above)
Comment (Technici4n) [reply src/tools_for_rules.jl:632]: Or maybe enforce `mode::Mode` in the _impl below

Comment (sunxd3) [reply src/tools_for_rules.jl:632]: I was thinking about the same thing, then decided to not change the behavior (thought these are somewhat internal). But yeah, throwing is more clear.

File: src/tools_for_rules.jl (hunk 2 above)
Comment (sunxd3) [reply src/tools_for_rules.jl:718]: Yep, just didn't like seeing the noops in the generated code.

**Comment by sunxd3** [comment]
Thanks for the review, Bruno

**Review by Technici4n — APPROVED** [review]

**Comment by Technici4n** [comment]
It looks like there is a DispatchDoctor failure, that could just be a 1.12 problem in DispatchDoctor, so you can probably ignore it and merge this PR. Remember to update the package version before doing so.
