### PR TITLE
fix for Base.CoreLogging usage in SciML solvers

### LINKED ISSUE #310: Support for println / IO in general?
This isn't Turing.jl test-suite related, but I often stick `@show` inside DynamicPPL functions to see what's going on, and that usually leads to errors if I try to run sampling with AD.

The example below errors, and the same happens with `println(x)`. Would it be possible to support this, or is it too awkward?

```julia
using DifferentiationInterface
import Mooncake

function f(x)
    @show x
    return x
end
backend = AutoMooncake(; config=nothing)
prep = prepare_gradient(f, backend, 1.0)
```

Traceback

```
julia> prep = prepare_gradient(f, backend, 1.0)
x = 1.0
┌ Warning: Unable to put rule in rule field. Rule should error.
└ @ Mooncake ~/.julia/packages/Mooncake/PS8NG/src/interpreter/s2s_reverse_mode_ad.jl:1487
MethodInstance is
MethodInstance for Base.var"#sprint#501"(::Nothing, ::Int64, ::typeof(sprint), ::Function, ::Float64)

with signature
Tuple{Base.var"##sprint#501", Nothing, Int64, typeof(sprint), Function, Float64}

derived_rule is of type
Mooncake.DerivedRule{Tuple{Base.var"##sprint#501", Nothing, Int64, typeof(sprint), Function, Tuple{Float64}}, MistyClosures.MistyClosure{Core.OpaqueClosure{Tuple{Mooncake.CoDual{Base.var"##sprint#501", Mooncake.NoFData}, Mooncake.CoDual{Nothing, Mooncake.NoFData}, Mooncake.CoDual{Int64, Mooncake.NoFData}, Mooncake.CoDual{typeof(sprint), Mooncake.NoFData}, Mooncake.CoDual, Mooncake.CoDual{Tuple{Float64}, Mooncake.NoFData}}, Union{}}}, MistyClosures.MistyClosure{Core.OpaqueClosure{Tuple{Mooncake.NoRData}, Tuple{Mooncake.NoRData, Mooncake.NoRData, Mooncake.NoRData, Mooncake.NoRData, Any, Tuple{Float64}}}}, Val{true}, Val{6}}

Expected type is
Mooncake.DerivedRule{Tuple{Base.var"##sprint#501", Nothing, Int64, typeof(sprint), Function, Tuple{Float64}}, MistyClosures.MistyClosure{Core.OpaqueClosure{Tuple{Mooncake.CoDual{Base.var"##sprint#501", Mooncake.NoFData}, Mooncake.CoDual{Nothing, Mooncake.NoFData}, Mooncake.CoDual{Int64, Mooncake.NoFData}, Mooncake.CoDual{typeof(sprint), Mooncake.NoFData}, Mooncake.CoDual, Mooncake.CoDual{Tuple{Float64}, Mooncake.NoFData}}, Mooncake.CoDual{String, Mooncake.NoFData}}}, MistyClosures.MistyClosure{Core.OpaqueClosure{Tuple{Mooncake.NoRData}, Tuple{Mooncake.NoRData, Mooncake.NoRData, Mooncake.NoRData, Mooncake.NoRData, Any, Tuple{Float64}}}}, Val{true}, Val{6}}

ERROR: UndefVarError: `args` not defined
Stacktrace:
  [1] _build_rule!(rule::Mooncake.LazyDerivedRule{Tuple{…}, Mooncake.DerivedRule{…}})
    @ Mooncake ~/.julia/packages/Mooncake/PS8NG/src/interpreter/s2s_reverse_mode_ad.jl:1500
  [2] LazyDerivedRule
    @ ~/.julia/packages/Mooncake/PS8NG/src/interpreter/s2s_reverse_mode_ad.jl:1506 [inlined]
  [3] f
    @ ./REPL[25]:2 [inlined]
  [4] (::Tuple{…})(none::Mooncake.CoDual{…}, none::Mooncake.CoDual{…})
    @ Base.Experimental ./<missing>:0
  [5] (::MistyClosures.MistyClosure{Core.OpaqueClosure{Tuple{…}, Mooncake.CoDual{…}}})(::Mooncake.CoDual{typeof(f), Mooncake.NoFData}, ::Mooncake.CoDual{Float64, Mooncake.NoFData})
    @ MistyClosures ~/.julia/packages/MistyClosures/4rFSA/src/MistyClosures.jl:22
  [6] DerivedRule
    @ ~/.julia/packages/Mooncake/PS8NG/src/interpreter/s2s_reverse_mode_ad.jl:739 [inlined]
  [7] __value_and_pullback!!(::Mooncake.DerivedRule{…}, ::Float64, ::Mooncake.CoDual{…}, ::Mooncake.CoDual{…})
    @ Mooncake ~/.julia/packages/Mooncake/PS8NG/src/interface.jl:14
  [8] value_and_pullback!!(::Mooncake.DerivedRule{Tuple{…}, MistyClosures.MistyClosure{…}, MistyClosures.MistyClosure{…}, Val{…}, Val{…}}, ::Float64, ::Function, ::Float64)
    @ Mooncake ~/.julia/packages/Mooncake/PS8NG/src/interface.jl:117
  [9] value_and_pullback(::Function, ::DifferentiationInterfaceMooncakeExt.MooncakeOneArgPullbackPrep{Float64, Mooncake.DerivedRule{…}, Float64, Float64}, ::AutoMooncake{Nothing}, ::Float64, ::Tuple{Bool})
    @ DifferentiationInterfaceMooncakeExt ~/.julia/packages/DifferentiationInterface/tBGja/ext/DifferentiationInterfaceMooncakeExt/onearg.jl:36
 [10] prepare_pullback(::Function, ::AutoMooncake{Nothing}, ::Float64, ::Tuple{Bool})
    @ DifferentiationInterfaceMooncakeExt ~/.julia/packages/DifferentiationInterface/tBGja/ext/DifferentiationInterfaceMooncakeExt/onearg.jl:22
 [11] prepare_gradient(::typeof(f), ::AutoMooncake{Nothing}, ::Float64)
    @ DifferentiationInterface ~/.julia/packages/DifferentiationInterface/tBGja/src/first_order/gradient.jl:70
 [12] top-level scope
    @ REPL[27]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by AstitvaAggarwal**
I still need to add tests, but you can verify the usage by running code in issue #657 . @yebai @ChrisRackauckas suggestions on code are welcome.

I've added comments for the LLVM call error above the rule for the same (handle thread safe counters/reads) , the rules following it are specific to Base.CoreLogging's functions that use logstate etc. (specifically when logging selection does NOT affect numerical solver data, handles observation side effects like   @info etc), a few string manipulation Base functions (string operations).

```
julia> using Mooncake, OrdinaryDiffEq, StaticArrays
       function lorenz!(du, u, p, t)
           du[1] = 10.0(u[2] - u[1])
           du[2] = u[1] * (28.0 - u[3]) - u[2]
           du[3] = u[1] * u[2] - (8 / 3) * u[3]
       end

       const _saveat = SA[0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0]

       function f(u0::Array{Float64})
           tspan = (0.0, 3.0)
           prob = ODEProblem{true,SciMLBase.FullSpecialize}(lorenz!, u0, tspan)
           sol = DiffEqBase.solve(prob, Tsit5(), saveat=_saveat, sensealg=DiffEqBase.SensitivityADPassThrough())
           sum(sol)
       end;

       rule = Mooncake.build_rrule(f, u0)
       mooncake_gradient(f, x) = Mooncake.value_and_gradient!!(rule, f, x)[2][2]
       mooncake_gradient(f, u0)
3-element Vector{Float64}:
     2.1072998565112364
   -31.089921681997474
 -1329.570875130246

julia> 
```

Fix https://github.com/chalk-lab/Mooncake.jl/issues/657 
Also covers/closes  #310 .

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by yebai** [comment]
@sunxd3, can you also help take a look?

File: src/rrules/avoiding_non_differentiable_code.jl [hunk 1]
```diff
@@ -14,25 +14,190 @@ end
...
             ),
-            2,
-        ),],
+
+            # Rules for handling Atomic read operations.
+            (
+                false,
+                :stability_and_allocs,
+                nothing,
+                Base.getindex,
```
Comment (yebai) [inline src/rrules/avoiding_non_differentiable_code.jl]: For consistency, let's use `Base.getindex` or `getindex` for all tests here. 
```suggestion
                getindex,
```

File: src/rrules/avoiding_non_differentiable_code.jl [hunk 2]
```diff
@@ -66,5 +241,36 @@ end
...
+    function testloggingmacro3(x)
+        @error "Testing @error macro"
+    end
+
+    function testloggingmacro4(x)
+        @debug "Testing @debug macro"
+    end
+
+    x = rand(1:100)
+    function testloggingmacro5(x)
```
Comment (yebai) [inline src/rrules/avoiding_non_differentiable_code.jl]:
```suggestion
    function testloggingmacro5(x; kw1=rand(1:100))
```

File: src/rrules/avoiding_non_differentiable_code.jl [hunk 3]
```diff
@@ -66,5 +241,36 @@ end
...
+        @info "Testing @info macro with kwargs" x
```
Comment (yebai) [inline src/rrules/avoiding_non_differentiable_code.jl]:
```suggestion
        @info "Testing @info macro with kwargs" kw1
```

File: src/rrules/avoiding_non_differentiable_code.jl [hunk 4]
```diff
@@ -14,25 +14,190 @@ end
...
+# in encountering a Atomic->Int address bitcast followed by a llvm atomic load call 
+@is_primitive MinimalCtx Tuple{typeof(getindex),Atomic{T}} where {T<:Integer}
+function rrule!!(::CoDual{typeof(getindex)}, x::CoDual{Atomic{T}}) where {T<:Integer}
+    pb!!(ȳ::NoRData) = NoRData(), NoRData()
+    return zero_fcodual(getindex(x.x)), pb!!
+end
+
+@is_primitive MinimalCtx Tuple{typeof(Base.normpath),String}
+function rrule!!(::CoDual{typeof(Base.normpath)}, path::CoDual{String})
+    pb!!(ȳ::NoRData) = NoRData(), NoRData()
```
Comment (yebai) [inline src/rrules/avoiding_non_differentiable_code.jl]: Is there a reason not to use `NoPullback()`?

**Review by yebai — CHANGES_REQUESTED** [review]
I left a few questions and suggestions.

File: src/rrules/avoiding_non_differentiable_code.jl (hunk 4 above)
Comment (sunxd3) [reply src/rrules/avoiding_non_differentiable_code.jl]: or maybe look into https://chalk-lab.github.io/Mooncake.jl/stable/utilities/defining_rules/#Functions-with-Zero-Adjoint?

Comment (AstitvaAggarwal) [reply src/rrules/avoiding_non_differentiable_code.jl]: Yes this is how the rules will finally look. Avoided this mainly as the kwarg rule is for a builtin and requires a handwritten rrule.

File: src/rrules/avoiding_non_differentiable_code.jl [hunk 5]
```diff
@@ -14,25 +14,151 @@ end
...
+    String,
+    Module,
+    Symbol,
+    Symbol,
+    String,
+    Int64,
+}
+# specialized case for Builtin primitive Core._call_latest rrule for CoreLogging.handle_message kwargs call. 
+@is_primitive MinimalCtx Tuple{
+    typeof(Core._call_latest),
```
Comment (yebai) [inline src/rrules/avoiding_non_differentiable_code.jl:80]: Quick question, why do we use `Core._call_latest` here but not in the other `kwcall` [rule](https://github.com/chalk-lab/Mooncake.jl/pull/669/files#diff-41cb2b3ecbee8eea05fcec16a70a3a72284a7db1a6139741658417e1a56e7c3bR38)?

Comment (AstitvaAggarwal) [reply src/rrules/avoiding_non_differentiable_code.jl:80]: In the IR for methods calling `sprint` and alike downstream, `Core._call_latest` does not appear (as the method definition is fixed). My guess is `CoreLogging` requires the latest method definition to be called i.e Dynamic Method Invocation (to see and work with the current logstate etc info), this leads to the lowered IR function name to change with each new call. The logstate information is recursive in nature as well, so if  `@logmsg` macros are called (or `handle_message` at lowered level) without `Base.invokelatest/Core._call_latest` it calls the current logstate itself - will lead to a stack overflow.

**Comment by AstitvaAggarwal** [comment]
thats wierd on julia v1.10.10, tests pass locally, but idk whats going on in CI.
```

(Mooncakebugs) pkg> st
Status `C:\Users\astit\OneDrive\Desktop\GSOC\Julia\contri\Mooncakebugs\Project.toml`
  [9b6a8646] AllocCheck v0.2.2
  [7057c7e9] Cassette v0.3.14
  [082447d4] ChainRules v1.72.5
  [d360d2e6] ChainRulesCore v1.25.2
⌃ [31a5f54b] Debugger v0.7.11
  [2b5f629d] DiffEqBase v6.177.1 `C:\Users\astit\.julia\dev\DiffEqBase`
⌃ [a0c0ee7d] DifferentiationInterface v0.7.1
⌃ [7da242da] Enzyme v0.13.57
  [6a86dc24] FiniteDiff v2.27.0
⌃ [587475ba] Flux v0.16.4
⌅ [f6369f11] ForwardDiff v0.10.38
  [b6b21f68] Ipopt v1.10.6
⌅ [c3a54625] JET v0.9.18
  [687ffad2] MacroModelling v0.1.40
  [dbe65cb8] MistyClosures v2.0.0
⌃ [961ee093] ModelingToolkit v9.68.1
  [da2b9cff] Mooncake v0.4.143 `C:\Users\astit\OneDrive\Desktop\GSOC\Julia\contri\Mooncake.jl`
  [7f7a1694] Optimization v4.4.0 `C:\Users\astit\.julia\dev\Optimization`
  [fd9f6733] OptimizationMOI v0.5.5
  [36348300] OptimizationOptimJL v0.4.3
⌃ [1dea7af3] OrdinaryDiffEq v6.98.0
  [bbf590c4] OrdinaryDiffEqCore v1.26.2 `C:\Users\astit\.julia\dev\OrdinaryDiffEq\lib/OrdinaryDiffEqCore`
⌃ [b1df2697] OrdinaryDiffEqTsit5 v1.1.0
  [37e2e3b7] ReverseDiff v1.16.1
⌃ [0bca4576] SciMLBase v2.102.1
⌃ [1ed8b502] SciMLSensitivity v7.87.0
  [860ef19b] StableRNGs v1.0.3
  [aedffcd0] Static v1.2.0
  [90137ffa] StaticArrays v1.9.14
  [9f7883ad] Tracker v0.2.38
  [e88e6eb3] Zygote v0.7.10
Info Packages marked with ⌃ and ⌅ have new versions available. Those with ⌃ may be upgradable, but those with ⌅ are restricted by compatibility constraints from upgrading. To see why use `status --outdated`

julia>   Mooncake.build_rrule(Mooncake.MooncakeInterpreter(), Tuple{typeof(println), String, String}; debug_mode=false)
Mooncake.DerivedRule{Tuple{typeof(println), Tuple{String, String}}, Tuple{Mooncake.CoDual{typeof(println), Mooncake.NoFData}, Mooncake.CoDual{Tuple{String, String}, Mooncake.NoFData}}, Mooncake.CoDual{Nothing, Mooncake.NoFData}, Tuple{Mooncake.NoRData}, Tuple{Mooncake.NoRData, Mooncake.NoRData}, true, Val{2}}(MistyClosure (::Mooncake.CoDual{typeof(println), Mooncake.NoFData}, ::Mooncake.CoDual{Tuple{String, 
String}, Mooncake.NoFData})::Mooncake.CoDual{Nothing, Mooncake.NoFData}->◌, Base.RefValue{MistyClosures.MistyClosure{Core.OpaqueClosure{Tuple{Mooncake.NoRData}, Tuple{Mooncake.NoRData, Mooncake.NoRData}}}}(MistyClosure (::Mooncake.NoRData)::Tuple{Mooncake.NoRData, Mooncake.NoRData}->◌), Val{2}())

```
