### PR TITLE
Fix tangent_type for Union{NoRData, RData{...}}

### LINKED ISSUE #1130: missing tangent_type method
### MWE

```julia
using Mooncake

struct LoHi{T}
    lo::T
    hi::T
end

LoHi(::Missing, ::Missing) = nothing # yes, I know this is bad style

struct Unit
    lohi::Union{Nothing,LoHi{Float64}}
end

calculation(lohi::LoHi, x) = x - (lohi.hi + lohi.lo) / 2

calculation(::Nothing, x) = x

calculation(unit::Unit, x) = calculation(unit.lohi, x)

struct Container
    units::Vector{Unit}
end

function (container::Container)(x)
    mapreduce(calculation, +, container.units, x)
end

c = Container([Unit(((x, y) = rand(2);
                     x < y ? LoHi(x, y) : LoHi(missing, missing)))
               for _ in 1:10])

x = randn(10);
c(x)                            # works fine
grad_cache = Mooncake.prepare_gradient_cache(c, x); # <- fails
val, grad = Mooncake.value_and_gradient!!(grad_cache, c, x);
```

### stacktrace and versions

```julia
julia> grad_cache = Mooncake.prepare_gradient_cache(c, x);
ERROR: MethodError: no method matching tangent_type(::Type{Mooncake.NoFData}, ::Type{Union{Mooncake.NoRData, Mooncake.RData{@NamedTuple{lo::Float64, hi::Float64}}}})
The function `tangent_type` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  tangent_type(::Type{Mooncake.NoFData}, ::Type{Mooncake.NoRData})
   @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/tangents/fwds_rvs_data.jl:891
  tangent_type(::Type{Mooncake.NoFData}, ::Type{Core.BFloat16})
   @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/rules/bfloat16.jl:13
  tangent_type(::Type{Mooncake.NoFData}, ::Type{R}) where R<:Tuple
   @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/tangents/fwds_rvs_data.jl:930
  ...

Stacktrace:
  [1] macro expansion
    @ ./none:-1 [inlined]
  [2] tangent_type(::Type{Tuple{Mooncake.NoFData}}, ::Type{Tuple{Union{Mooncake.NoRData, Mooncake.RData{@NamedTuple{lo::Float64, hi::Float64}}}}})
    @ Mooncake ./none:0
  [3] tangent_type(::Type{Mooncake.NoFData}, ::Type{Tuple{Union{Mooncake.NoRData, Mooncake.RData{@NamedTuple{lo::Float64, hi::Float64}}}}})
    @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/tangents/fwds_rvs_data.jl:931
  [4] tangent_type(::Type{Mooncake.NoFData}, ::Type{@NamedTuple{lohi::Union{Mooncake.NoRData, Mooncake.RData{@NamedTuple{lo::Float64, hi::Float64}}}}})
    @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/tangents/fwds_rvs_data.jl:944
  [5] tangent_type(::Type{Mooncake.NoFData}, ::Type{Mooncake.RData{@NamedTuple{lohi::Union{Mooncake.NoRData, Mooncake.RData{@NamedTuple{lo::Float64, hi::Float64}}}}}})
    @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/tangents/fwds_rvs_data.jl:959
  [6] tangent(::Mooncake.NoFData, r::Mooncake.RData{@NamedTuple{lohi::Union{Mooncake.NoRData, Mooncake.RData{@NamedTuple{lo::Float64, hi::Float64}}}}})
    @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/tangents/fwds_rvs_data.jl:1007
  [7] increment_rdata!!(t::Mooncake.Tangent{@NamedTuple{lohi::Union{Mooncake.NoTangent, Mooncake.Tangent{…}}}}, r::Mooncake.RData{@NamedTuple{lohi::Union{Mooncake.NoRData, Mooncake.RData{…}}}})
    @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/tangents/fwds_rvs_data.jl:1038
  [8] (::Mooncake.var"#lmemoryrefget_adjoint#rrule!!##107"{MemoryRef{Mooncake.Tangent{…}}, Val{false}, Val{:not_atomic}})(dy::Mooncake.RData{@NamedTuple{lohi::Union{…}}})
    @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/rules/memory.jl:429
  [9] (::Mooncake.RRuleWrapperPb{Mooncake.var"#lmemoryrefget_adjoint#rrule!!##107"{…}, Mooncake.LazyZeroRData{…}})(dy::Mooncake.RData{@NamedTuple{…}})
    @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/interpreter/reverse_mode.jl:324
 [10] getindex
    @ ./essentials.jl:919 [inlined]
 [11] pop!
    @ ~/.julia/packages/Mooncake/jsPfZ/src/stack.jl:31 [inlined]
 [12] __pop_blk_stack!
    @ ~/.julia/packages/Mooncake/jsPfZ/src/interpreter/reverse_mode.jl:1868 [inlined]
 [13] collect
    @ ./array.jl:784 [inlined]
 [14] (::Tuple{…})(_2::Mooncake.NoRData)
    @ Base.Experimental ./<missing>:0
 [15] (::MistyClosures.MistyClosure{Core.OpaqueClosure{Tuple{Mooncake.NoRData}, Tuple{Mooncake.NoRData, Mooncake.NoRData}}})(x::Mooncake.NoRData)
    @ MistyClosures ~/.julia/packages/MistyClosures/2vtLL/src/MistyClosures.jl:22
 [16] Pullback
    @ ~/.julia/packages/Mooncake/jsPfZ/src/interpreter/reverse_mode.jl:957 [inlined]
 [17] Container
    @ ./REPL[21]:2 [inlined]
 [18] (::Tuple{…})(_2::Float64)
    @ Base.Experimental ./<missing>:0
 [19] (::MistyClosures.MistyClosure{Core.OpaqueClosure{Tuple{Float64}, Tuple{Mooncake.NoRData, Mooncake.NoRData}}})(x::Float64)
    @ MistyClosures ~/.julia/packages/MistyClosures/2vtLL/src/MistyClosures.jl:22
 [20] (::Mooncake.Pullback{Tuple{Container, Vector{Float64}}, Tuple{Float64}, Tuple{Mooncake.NoRData, Mooncake.NoRData}, false, 2})(dy::Float64)
    @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/interpreter/reverse_mode.jl:957
 [21] prepare_gradient_cache(::Container, ::Vararg{Any}; config::Mooncake.Config)
    @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/interface.jl:779
 [22] prepare_gradient_cache(::Container, ::Vararg{Any})
    @ Mooncake ~/.julia/packages/Mooncake/jsPfZ/src/interface.jl:774
 [23] top-level scope
    @ REPL[25]:1
Some type information was truncated. Use `show(err)` to see complete types.

julia> VERSION
v"1.12.5"

(Mooncake-debug) pkg> st
Status `~/research/spouses-time-allocation/CouplesTimeuse/debug/Mooncake-debug/Project.toml`
  [da2b9cff] Mooncake v0.5.25 `https://github.com/chalk-lab/Mooncake.jl#main`
```

### PR DESCRIPTION
**Pull request by yebai**
## Summary

`tangent_type(NoFData, R)` previously only handled `R <: Union{NoRData, IEEEFloat}`, causing a missing-method error when `R` contained an `RData{...}`  branch (e.g. `Union{Nothing, LoHi}` where `LoHi` has only `Float64` fields , `fdata` collapses to `NoFData` but `rdata` is `Union{NoRData, RData{...}})`.                
                  
This PR fixes that and handles the full set of union cases that arise from `Union{Nothing, T}` struct fields, three new dispatch methods (plus two tiebreakers to resolve Julia method ambiguities):
                                                                                
1. `tangent_type(NoFData, R) where R<:Union{NoRData,IEEEFloat,RData}` — the core fix: extends the existing method to cover `RData{...}` branches, not just 
  scalars.                                                                      
2. `tangent_type(F, R) where F<:Union{NoFData,FData}, R<:Union{NoRData,RData}` — handles the fully mixed case where `T` has both scalar and heap-allocated      
  fields, making both `F` and `R` proper unions simultaneously.
3. `tangent_type(F, NoRData) where F<:Union{NoFData,FData}` — tiebreaker for when only `F` is a union (e.g. `Union{Nothing, VecOnly}` where `VecOnly` has only   
  Vector fields).
                                                                                
`_validate_union` fix : the old check `rdata_type(tangent_type(_T)) != NoRData` was conceptually wrong (treating an `fdata` type as a primal) and silently passed primitives like `Int64` since `tangent_type(Int64) = NoTangent` → `rdata = NoRData`.
Replaced with `isprimitivetype(_T) || rdata_type(_T) != NoRData` — the isprimitivetype guard is also necessary because `rdata_type` itself throws for non-`IEEEFloat` primitives.

Split from #1132 for easier review.  Closes #1130. 

### Documentation Preview

Mooncake.jl documentation for PR #1133 is available at:
https://chalk-lab.github.io/Mooncake.jl/previews/PR1133/

### Performance

Performance Ratio:
Ratio of time to compute gradient and time to compute function.
Warning: results are very approximate! See [here](https://github.com/chalk-lab/Mooncake.jl/tree/main/bench#inter-framework-benchmarking) for more context.
```
┌───────────────────────┬──────────┬──────────┬─────────────┬─────────┬─────────────┬────────┐
│                 Label │   Primal │ Mooncake │ MooncakeFwd │  Zygote │ ReverseDiff │ Enzyme │
│                String │   String │   String │      String │  String │      String │ String │
├───────────────────────┼──────────┼──────────┼─────────────┼─────────┼─────────────┼────────┤
│              sum_1000 │ 211.0 ns │     1.38 │        1.43 │   0.569 │        2.75 │   5.32 │
│             _sum_1000 │ 952.0 ns │     7.05 │        1.03 │  4400.0 │        38.7 │   1.08 │
│          sum_sin_1000 │  7.45 μs │     3.46 │        1.35 │    1.47 │        10.7 │    1.7 │
│         _sum_sin_1000 │  6.85 μs │     3.39 │        1.72 │   308.0 │        11.8 │   1.91 │
│              kron_sum │ 255.0 μs │     12.5 │        3.63 │    10.2 │       436.0 │   17.8 │
│         kron_view_sum │ 350.0 μs │     10.2 │        5.05 │    23.6 │       410.0 │   6.63 │
│ naive_map_sin_cos_exp │   2.7 μs │     2.92 │         1.5 │ missing │         6.6 │   1.85 │
│       map_sin_cos_exp │  2.51 μs │     3.49 │        1.61 │    1.49 │        6.17 │   2.44 │
│ broadcast_sin_cos_exp │  2.64 μs │     2.95 │        1.59 │    4.72 │        1.27 │   1.88 │
│            simple_mlp │ 489.0 μs │     4.39 │         2.7 │    1.82 │        8.15 │   2.79 │
│                gp_lml │ 534.0 μs │     5.15 │        1.72 │    2.47 │     missing │   2.81 │
│    large_single_block │ 471.0 ns │     7.91 │         2.1 │  4320.0 │        28.3 │   1.83 │
└───────────────────────┴──────────┴──────────┴─────────────┴─────────┴─────────────┴────────┘
```

### CODE REVIEW

File: src/tangents/fwds_rvs_data.jl [hunk 1]
```diff
@@ -892,33 +892,71 @@ tangent type. This method must be equivalent to `tangent_type(_typeof(primal))`.
...
+            end
+        end
+    end
+    return nothing
+end
+function _validate_rdata_union(::Type{R}) where {R<:Union{NoRData,Base.IEEEFloat,RData}}
+    if R isa Union
+        _validate_rdata_union(R.a)
+        _validate_rdata_union(R.b)
+    elseif R != NoRData && fdata_type(tangent_type(NoFData, R)) != NoFData
```
Comment (sunxd3) [inline src/tangents/fwds_rvs_data.jl]: I fear the `tangent_type` here can produce similar error as line 931, should we catch it?

File: src/test_resources.jl [hunk 2]
```diff
@@ -184,6 +184,18 @@ struct P_adam_like
...
+struct LoHi
+    lo::Float64
+    hi::Float64
+end
+struct LoHiContainer
+    lohi::Union{Nothing,LoHi}
+end
+make_P_lohi_union() = LoHi(1.0, 2.0)::Union{Nothing,LoHi}
+make_P_lohi_container() = LoHiContainer(LoHi(1.0, 2.0))
+make_P_nothing_or_vector() = [1.0, 2.0]::Union{Nothing,Vector{Float64}}
```
Comment (sunxd3) [inline src/test_resources.jl]: it seems that Julia will still specialize the type instead of taking the Union type as hinted

**Review by sunxd3 — COMMENTED** [review]
thanks for initiating this!

**Comment by AstitvaAggarwal** [comment]
@yebai also requesting your reviews

File: src/tangents/fwds_rvs_data.jl [hunk 3]
```diff
@@ -888,33 +888,61 @@ end
...
+# Tiebreaker: without this, method above (more specific on F) and method below (more
+# specific on R) are both ambiguous for tangent_type(NoFData, Union{NoRData,RData{...}}).
+# This method beats both: exact F and tighter R bound.
+@foldable function tangent_type(::Type{NoFData}, ::Type{R}) where {R<:Union{NoRData,RData}}
+    @assert R isa Union
+    Union{tangent_type(NoFData, R.a),tangent_type(NoFData, R.b)}
+end
+@foldable function tangent_type(
+    ::Type{F}, ::Type{R}
+) where {F<:Union{NoFData,FData},R<:Union{NoRData,RData}}
```
Comment (sunxd3) [inline src/tangents/fwds_rvs_data.jl:927]: `Union{NoRData,RData{...},RData{...}} <: Union{NoRData,RData}` and might cause problem
