### PR TITLE
_copy_to_output!! error handling for mismatched types

### LINKED ISSUE #855: `_copy_to_output!!` not defined for non-differentiable types
```julia
using DifferentiationInterface
import Mooncake

f(x) = x
backend = AutoMooncake()
x = [1]
prep = prepare_jacobian(f, backend, x)
jacobian(f, prep, backend, x)
#=
ERROR: MethodError: no method matching _copy_to_output!!(::Vector{Mooncake.NoTangent}, ::Vector{Int64})
The function `_copy_to_output!!` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  _copy_to_output!!(::P, ::P) where P<:Union{Array, Memory}
   @ Mooncake ~/.julia/packages/Mooncake/zejlI/src/interface.jl:264
  _copy_to_output!!(::P, ::P) where P
   @ Mooncake ~/.julia/packages/Mooncake/zejlI/src/interface.jl:280
  _copy_to_output!!(::Core.SimpleVector, ::Core.SimpleVector)
   @ Mooncake ~/.julia/packages/Mooncake/zejlI/src/interface.jl:259
=#
```

I don't mind that Mooncake refuses to differentiate Ints, just think the error message could be nicer.

### PR DESCRIPTION
**Pull request by AstitvaAggarwal**
closes #855 

More about the error:

https://github.com/JuliaDiff/DifferentiationInterface.jl/blob/1da3a200f89a41e370fa8f771a2c7f1ff91ad2b6/DifferentiationInterface/ext/DifferentiationInterfaceMooncakeExt/onearg.jl#L40 causes the issue. Here, `DI` calls `Mooncake.copy_to_output!!` on incorrect arguments.
specifically `dst` is correct -
```
julia> prep.pullback_prep.dy_righttype
1-element Vector{Mooncake.NoTangent}:
 Mooncake.NoTangent()

```
, however `src` is -
``` 
julia> only(prep.batched_seeds)
([1],)
``` 
Therefore, these do not match in type and `src` cannot be copied into `dst`. 

For `src`'s correct creation - `DI`'s `prep` object's `batch_seeds` field must be expanded to handle `Mooncake.NoTangent`.
As currently via DI.basis here: https://github.com/JuliaDiff/DifferentiationInterface.jl/blob/1da3a200f89a41e370fa8f771a2c7f1ff91ad2b6/DifferentiationInterface/src/first_order/jacobian.jl#L213 we get :

```
julia> DifferentiationInterface.basis(x,1)
1-element Vector{Int64}:
 1
```

Therefore, this PR addresses the issue by addressing calling `Mooncake.copy_to_output!!` on incorrect arguments (fyi in the stacktrace, thats only where Mooncake is called).

```
julia> jacobian(f, prep, backend, x)
ERROR: MethodError: no method matching _copy_to_output!!(::Vector{Mooncake.NoTangent}, ::Vector{Int64})

Closest candidates are:
  _copy_to_output!!(::P, ::P) where P<:Array
   @ Mooncake C:\Users\astit\OneDrive\Desktop\GSOC\Julia\contri\Mooncake.jl\src\interface.jl:264
  _copy_to_output!!(::P, ::P) where P
   @ Mooncake C:\Users\astit\OneDrive\Desktop\GSOC\Julia\contri\Mooncake.jl\src\interface.jl:280

Stacktrace:
  [1] value_and_pullback(::typeof(f), ::DifferentiationInterfaceMooncakeExt.MooncakeOneArgPullbackPrep{…}, ::AutoMooncake{…}, ::Vector{…}, ::Tuple{…})
    @ DifferentiationInterfaceMooncakeExt C:\Users\astit\.julia\packages\DifferentiationInterface\4n6vR\ext\DifferentiationInterfaceMooncakeExt\onearg.jl:40
  [2] pullback(::typeof(f), ::DifferentiationInterfaceMooncakeExt.MooncakeOneArgPullbackPrep{…}, ::AutoMooncake{…}, ::Vector{…}, ::Tuple{…})
    @ DifferentiationInterfaceMooncakeExt C:\Users\astit\.julia\packages\DifferentiationInterface\4n6vR\ext\DifferentiationInterfaceMooncakeExt\onearg.jl:95
  [3] (::DifferentiationInterface.var"#77#78"{…})(a::Int64)
    @ DifferentiationInterface C:\Users\astit\.julia\packages\DifferentiationInterface\4n6vR\src\first_order\jacobian.jl:474
  [4] (::Base.var"#186#187"{DifferentiationInterface.var"#77#78"{…}})(x::Int64)
    @ Base .\none:0
  [5] iterate
    @ .\generator.jl:47 [inlined]
  [6] collect
    @ .\array.jl:834 [inlined]
  [7] _stack(dims::Int64, ::Base.HasShape{1}, iter::Base.Generator{Base.OneTo{…}, Base.var"#186#187"{…}})
    @ Base .\abstractarray.jl:2810
  [8] _stack(dims::Int64, iter::Base.Generator{Base.OneTo{…}, Base.var"#186#187"{…}})
    @ Base .\abstractarray.jl:2800
  [9] stack(f::DifferentiationInterface.var"#77#78"{…}, iter::Base.OneTo{…}; dims::Int64)
    @ Base .\abstractarray.jl:2797
 [10] _jacobian_aux(::Tuple{…}, ::DifferentiationInterface.PullbackJacobianPrep{…}, ::AutoMooncake{…}, ::Vector{…})
    @ DifferentiationInterface C:\Users\astit\.julia\packages\DifferentiationInterface\4n6vR\src\first_order\jacobian.jl:473
 [11] jacobian(::typeof(f), ::DifferentiationInterface.PullbackJacobianPrep{…}, ::AutoMooncake{…}, ::Vector{…})
    @ DifferentiationInterface C:\Users\astit\.julia\packages\DifferentiationInterface\4n6vR\src\first_order\jacobian.jl:273
 [12] top-level scope
    @ REPL[72]:1
Some type information was truncated. Use `show(err)` to see complete types.

julia> 

```

### CODE REVIEW

**Comment by Technici4n** [comment]
I don't think that this will be a very helpful message for a user encountering an issue like #855. This could probably be specialized to `NoTangent` and give a helpful error message such as "This typically happens when differentiating a non-differentiable function". But in that case I am not even sure why it's erroring. It's worth looking at _why_ this is happening.

**Comment by AstitvaAggarwal** [comment]
@Technici4n thank you for the review, I think the error is mainly due to DI calling only copying on incorrect arguments. so within Mooncake maybe we can only handle it best by making the copy function more robust?

Regarding handling NoTangent - Non differentiability, I think this must be handled within DI via a seperate PR to make the prep object creation handle this Tangent type. @gdalle can you also please give a review and let me know if what I understand about DI is correct? thanks!

**Comment by gdalle** [comment]
I'll take a look but probably not today, please don't merge in the meantime. What I'll say about DI is that we work based on the assumption that primal and tangent variables live in the same space. To me, the right fix isn't loosening Mooncake's utilities, but rather implementing a translation mechanism (#393 I believe) so that I can bring the tangents back into primal world and perform operations on them. This conversion mechanism would typically have converted `NoTangent()` into `[0]`

**Comment by gdalle** [comment]
Yeah I confirm that this error message doesn't tell much more than the `MethodError` one would otherwise get. The real solution probably lies in #860

**Comment by yebai** [comment]
We perform these [generic fallbacks](https://github.com/chalk-lab/Mooncake.jl/blob/01f70534118266a0ff368705f1a1a0109b5e49a0/src/tools_for_rules.jl#L362-L373) in several other places to catch misuse errors, so this is still useful. I tweaked the error message to make it more informative (hopefully).

File: src/interface.jl [hunk 1]
```diff
@@ -317,6 +317,19 @@ function _copy_to_output!!(dst::P, src::P) where {P}
     end
 end
 
+# fallback for invalid type combinations
+function _copy_to_output!!(dst::T, src::P) where {T,P}
+    throw(
+        ArgumentError(
+            "The types of dst and src do not match: " *
+            "dst passed is of type $T, while src is a $P.",
```
Comment (sunxd3) [inline src/interface.jl]:
```suggestion
            "dst passed is of type $T, while src is a $P. " *
```

File: src/interface.jl [hunk 2]
```diff
@@ -317,6 +317,19 @@ function _copy_to_output!!(dst::P, src::P) where {P}
...
+            "This is because Mooncake.jl does not currently have a method of " *
```
Comment (sunxd3) [inline src/interface.jl]:
```suggestion
            "Mooncake.jl does not currently have a method " *
```
drop a `this` to avoid repetition

File: src/interface.jl [hunk 3]
```diff
@@ -317,6 +317,19 @@ function _copy_to_output!!(dst::P, src::P) where {P}
...
+            "`_copy_to_output!!` to handle this type combination. " *
+            "This typically happens when differentiating a non-differentiable function.",
```
Comment (sunxd3) [inline src/interface.jl]:
```suggestion
            "This often happens when differentiating over " * 
            "non-differentiable types (e.g. integers or booleans).",
```
