### PR TITLE
1035 logsumexp subarray

### LINKED ISSUE #1035: Issues differentiating `LogExpFunctions.logsumexp`
As in the title, if I run:
```julia
using Turing, Mooncake, LogExpFunctions

@model function model_logsumexp()

    x ~ filldist(Normal(0, 1), 10)

    y = logsumexp(x)

    Turing.@addlogprob! sum(logpdf(Normal(0, 1), y))

end

samples = sample(model_logsumexp(), NUTS(; adtype = AutoMooncake()), 1000)
```
I get the error (full stacktrace at the end):
```julia
ERROR: MethodError: no method matching length(::Mooncake.FData{@NamedTuple{…}})
The function `length` exists, but no method is defined for this combination of argument types.
```
However, I do not get errors if I run
```julia
@model function model_log_sum_exp()

    x ~ filldist(Normal(0, 1), 10)

    y = log.(sum(exp, x))

    Turing.@addlogprob! sum(logpdf(Normal(0, 1), y))

end

@model function model_logaddexp()

    x ~ filldist(Normal(0, 1), 10)

    y = reduce(logaddexp, x)

    Turing.@addlogprob! sum(logpdf(Normal(0, 1), y))

end

samples = sample(model_logaddexp(), NUTS(; adtype = AutoMooncake()), 1000)
samples = sample(model_log_sum_exp(), NUTS(; adtype = AutoMooncake()), 1000)
```
I have used `logsumexp` in Turing models with Mooncake before so I'm not sure if this is related to the @model structure or a recent change.
Feel free to move the issue if Mooncake isn't the best place for this

On Mooncake version 0.5.14, Turing version 0.42.9, LogExpFunctions version 0.3.29, and julia version 1.12.5
Full trace:

```Julia
julia> samples = sample(model_logsumexp(), NUTS(; adtype = AutoMooncake()), 1000)
ERROR: MethodError: no method matching length(::Mooncake.FData{@NamedTuple{…}})
The function `length` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  length(::Markdown.MD)
   @ Markdown ~/.julia/juliaup/julia-1.12.5+0.x64.linux.gnu/share/julia/stdlib/v1.12/Markdown/src/parse/parse.jl:35
  length(::NamedArrays.Enamerate)
   @ NamedArrays ~/.julia/packages/NamedArrays/f1tMK/src/iterators.jl:20
  length(::Combinatorics.CoolLexCombinations)
   @ Combinatorics ~/.julia/packages/Combinatorics/Qubsi/src/combinations.jl:135
  ...

Stacktrace:
  [1] _similar_shape(itr::Mooncake.FData{@NamedTuple{…}}, ::Base.HasLength)
    @ Base ./array.jl:657
  [2] _collect(cont::UnitRange{Int64}, itr::Mooncake.FData{@NamedTuple{…}}, ::Base.HasEltype, isz::Base.HasLength)
    @ Base ./array.jl:734
  [3] collect(itr::Mooncake.FData{@NamedTuple{…}})
    @ Base ./array.jl:728
  [4] broadcastable(x::Mooncake.FData{@NamedTuple{…}})
    @ Base.Broadcast ./broadcast.jl:733
  [5] (::MooncakeLogExpFunctionsExt.var"#logsumexp_pb!!#rrule!!##2"{…})(dy::Float64)
    @ MooncakeLogExpFunctionsExt ~/.julia/packages/Mooncake/Bb8fK/ext/MooncakeLogExpFunctionsExt.jl:93
  [6] pop!
    @ ~/.julia/packages/Mooncake/Bb8fK/src/stack.jl:33 [inlined]
  [7] model_logsumexp
    @ ~/MYDOCS/logsumexp_turing.jl:3 [inlined]
  [8] (::Tuple{…})(_2::Tuple{…})
    @ Base.Experimental ./<missing>:0
  [9] (::MistyClosures.MistyClosure{Core.OpaqueClosure{…}})(x::Tuple{Mooncake.RData{…}, Mooncake.RData{…}})
    @ MistyClosures ~/.julia/packages/MistyClosures/2vtLL/src/MistyClosures.jl:22
 [10] Pullback
    @ ~/.julia/packages/Mooncake/Bb8fK/src/interpreter/reverse_mode.jl:957 [inlined]
 [11] logdensity_at
    @ ~/.julia/packages/DynamicPPL/Qf6tQ/src/logdensityfunction.jl:288 [inlined]
 [12] (::Tuple{Mooncake.Stack{…}, Base.RefValue{…}, Mooncake.LazyDerivedRule{…}, Mooncake.Stack{…}})(_2::Float64)
    @ Base.Experimental ./<missing>:0
 [13] (::MistyClosures.MistyClosure{Core.OpaqueClosure{Tuple{…}, Tuple{…}}})(x::Float64)
    @ MistyClosures ~/.julia/packages/MistyClosures/2vtLL/src/MistyClosures.jl:22
 [14] (::Mooncake.Pullback{Tuple{…}, Tuple{…}, Tuple{…}, false, 8})(dy::Float64)
    @ Mooncake ~/.julia/packages/Mooncake/Bb8fK/src/interpreter/reverse_mode.jl:957
 [15] prepare_gradient_cache(::Function, ::Vararg{Any}; config::Mooncake.Config)
    @ Mooncake ~/.julia/packages/Mooncake/Bb8fK/src/interface.jl:588
 [16] prepare_gradient_cache
    @ ~/.julia/packages/Mooncake/Bb8fK/src/interface.jl:583 [inlined]
 [17] prepare_gradient_nokwarg(::Val{…}, ::typeof(DynamicPPL.logdensity_at), ::AutoMooncake{…}, ::Vector{…}, ::DifferentiationInterface.Constant{…}, ::DifferentiationInterface.Constant{…}, ::DifferentiationInterface.Constant{…}, ::DifferentiationInterface.Constant{…}, ::DifferentiationInterface.Constant{…}, ::DifferentiationInterface.Constant{…})
    @ DifferentiationInterfaceMooncakeExt ~/.julia/packages/DifferentiationInterface/afUhd/ext/DifferentiationInterfaceMooncakeExt/onearg.jl:114
 [18] prepare_gradient(::typeof(DynamicPPL.logdensity_at), ::AutoMooncake{…}, ::Vector{…}, ::DifferentiationInterface.Constant{…}, ::DifferentiationInterface.Constant{…}, ::DifferentiationInterface.Constant{…}, ::DifferentiationInterface.Constant{…}, ::DifferentiationInterface.Constant{…}, ::DifferentiationInterface.Constant{…})
    @ DifferentiationInterface ~/.julia/packages/DifferentiationInterface/afUhd/src/first_order/gradient.jl:8
 [19] LogDensityFunction(model::DynamicPPL.Model{…}, getlogdensity::Function, varinfo::DynamicPPL.VarInfo{…}, accs::DynamicPPL.AccumulatorTuple{…}; adtype::AutoMooncake{…})
    @ DynamicPPL ~/.julia/packages/DynamicPPL/Qf6tQ/src/logdensityfunction.jl:218
 [20] initialstep(rng::Random.TaskLocalRNG, model::DynamicPPL.Model{…}, spl::NUTS{…}, vi_original::DynamicPPL.VarInfo{…}; initial_params::InitFromUniform{…}, nadapts::Int64, discard_sample::Bool, verbose::Bool, kwargs::@Kwargs{…})
    @ Turing.Inference ~/.julia/packages/Turing/csgsG/src/mcmc/hmc.jl:202
 [21] step(rng::Random.TaskLocalRNG, model::DynamicPPL.Model{…}, spl::NUTS{…}; initial_params::InitFromUniform{…}, kwargs::@Kwargs{…})
    @ Turing.Inference ~/.julia/packages/Turing/csgsG/src/mcmc/abstractmcmc.jl:182
 [22] step
    @ ~/.julia/packages/Turing/csgsG/src/mcmc/abstractmcmc.jl:164 [inlined]
 [23] step_warmup
    @ ~/.julia/packages/AbstractMCMC/oqm6Y/src/interface.jl:118 [inlined]
 [24] #_step_or_step_warmup#25
    @ ~/.julia/packages/AbstractMCMC/oqm6Y/src/sample.jl:126 [inlined]
 [25] _step_or_step_warmup
    @ ~/.julia/packages/AbstractMCMC/oqm6Y/src/sample.jl:124 [inlined]
 [26] macro expansion
    @ ~/.julia/packages/AbstractMCMC/oqm6Y/src/sample.jl:223 [inlined]
 [27] macro expansion
    @ ~/.julia/packages/AbstractMCMC/oqm6Y/src/logging.jl:137 [inlined]
 [28] mcmcsample(rng::Random.TaskLocalRNG, model::DynamicPPL.Model{…}, sampler::NUTS{…}, N::Int64; progress::Bool, progressname::String, callback::Nothing, num_warmup::Int64, discard_initial::Int64, thinning::Int64, chain_type::Type, initial_state::Nothing, kwargs::@Kwargs{…})
    @ AbstractMCMC ~/.julia/packages/AbstractMCMC/oqm6Y/src/sample.jl:204
 [29] sample(rng::Random.TaskLocalRNG, model::DynamicPPL.Model{…}, sampler::NUTS{…}, N::Int64; check_model::Bool, chain_type::Type, initial_params::InitFromUniform{…}, initial_state::Nothing, progress::Bool, nadapts::Int64, discard_adapt::Bool, discard_initial::Int64, kwargs::@Kwargs{})
    @ Turing.Inference ~/.julia/packages/Turing/csgsG/src/mcmc/hmc.jl:121
 [30] sample
    @ ~/.julia/packages/Turing/csgsG/src/mcmc/hmc.jl:88 [inlined]
 [31] #sample#1
    @ ~/.julia/packages/Turing/csgsG/src/mcmc/abstractmcmc.jl:73 [inlined]
 [32] sample(model::DynamicPPL.Model{…}, spl::NUTS{…}, N::Int64)
    @ Turing.Inference ~/.julia/packages/Turing/csgsG/src/mcmc/abstractmcmc.jl:70
 [33] top-level scope
    @ ~/MYDOCS/logsumexp_turing.jl:13
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by GBarnsley**
Closes #1035

Added support for `SubArrays` / `views` to rules in LogExpFunctionsExt with `arrayify`. 

Have also added some views to the tests for these functions.

Please double-check since I'm not super familiar with Mooncake's internals, but now seems to match logsumexp grads using Arrays on my end.

```julia
using Mooncake, LogExpFunctions

f(x) = logsumexp(x)
x_array = [0.1, 0.2, 0.3]
x_view = view(x_array, 1:3)

val_view, grad_view = Mooncake.value_and_gradient!!(Mooncake.prepare_gradient_cache(f, x_view), f, x_view)

val_array, grad_array = Mooncake.value_and_gradient!!(Mooncake.prepare_gradient_cache(f, x_array), f, x_array)

grad_view[2].fields.parent == grad_array[2]
# though grad_view[2] is a tangent and grad_array[2] is a vector?
```

### CODE REVIEW

File: ext/MooncakeLogExpFunctionsExt.jl
Comment (yebai) [inline ext/MooncakeLogExpFunctionsExt.jl]:
```suggestion
    xp, dx = arrayify(x)
```

File: ext/MooncakeLogExpFunctionsExt.jl [hunk 1]
```diff
@@ -55,6 +67,18 @@ function frule!!(
     end
     return Dual(y, dy)
 end
+function frule!!(
```
Comment (yebai) [inline ext/MooncakeLogExpFunctionsExt.jl]: If one makes the change above for L63 (extract --> arrayify), these separate rules for SubArray or similiars would no longer be needed. The purpose of `arrify` is to canonicalise input arguments so we can write more general rules. 

https://chalk-lab.github.io/Mooncake.jl/stable/utilities/defining_rules/#Canonicalising-Tangent-Types


The same goes for the other rules.

Comment (GBarnsley) [reply ext/MooncakeLogExpFunctionsExt.jl]: That makes sense, have updated the methods

**Comment by GBarnsley** [comment]
Have updated to use `arrayify` in the `<:AbstractArray` methods, and also expanded to include `logsumexp!` as well, since that also need `arrayify`ing for SubArrays.
Have also applied JuliaFormatter.
Will squash commits before merging, once it has been reviewed.

File: ext/MooncakeLogExpFunctionsExt.jl [hunk 2]
```diff
@@ -103,8 +105,10 @@ end
 function frule!!(
     ::Dual{typeof(logsumexp!)}, out::Dual{<:AbstractArray{P}}, x::Dual{<:AbstractArray{P}}
 ) where {P<:IEEEFloat}
-    logsumexp!(primal(out), primal(x))
-    sum!(tangent(out), tangent(x) .* exp.(primal(x) .- primal(out)))
+    px, dx = arrayify(x)
+    y, dy = arrayify(out)
+    logsumexp!(primal(out), px)
```
Comment (yebai) [inline ext/MooncakeLogExpFunctionsExt.jl]:
```suggestion
    logsumexp!(y, px)
```

File: ext/MooncakeLogExpFunctionsExt.jl [hunk 3]
```diff
@@ -113,11 +117,11 @@ function rrule!!(
     x::CoDual{<:AbstractArray{P}},
 ) where {P<:IEEEFloat}
     old_out = copy(primal(out))
-    logsumexp!(primal(out), primal(x))
-    y, dy = extract(out)
-    dx = tangent(x)
+    px, dx = arrayify(x)
```
Comment (yebai) [inline ext/MooncakeLogExpFunctionsExt.jl]:
```suggestion
    px, dx = arrayify(x)
    y, dy = arrayify(out)
```

File: ext/MooncakeLogExpFunctionsExt.jl [hunk 4]
```diff
@@ -113,11 +117,11 @@ function rrule!!(
...
+    logsumexp!(primal(out), px)
```
Comment (yebai) [inline ext/MooncakeLogExpFunctionsExt.jl]:
```suggestion
    logsumexp!(y, px)
```

File: ext/MooncakeLogExpFunctionsExt.jl [hunk 5]
```diff
@@ -113,11 +117,11 @@ function rrule!!(
...
+    y, dy = arrayify(out)
```
Comment (yebai) [inline ext/MooncakeLogExpFunctionsExt.jl]:
```suggestion
```

**Comment by GBarnsley** [comment]
Ready to merge @AstitvaAggarwal @yebai . Great package!
